" General Configuration
set nocompatible
filetype indent plugin on
syntax on
set t_ut=
set nobackup
set nowritebackup
set noswapfile
set number
set relativenumber
set history=500
set showmode
set visualbell
set autoread
set hidden
set autoindent
set copyindent
set smarttab
set noet
set tabstop=4
set shiftwidth=4
set showmatch
set backspace=indent,eol,start
set scrolloff=5
set laststatus=2
set incsearch
set hlsearch
set showcmd
set ignorecase
set smartcase
set splitbelow
set splitright
set wildmode=longest,list,full
set wildmenu
set path+=**
set timeoutlen=500 ttimeoutlen=0
set completeopt+=noinsert
set updatetime=100
set confirm
set helpheight=100
set listchars=eol:¬,tab:>-,trail:~,extends:>,precedes:<,space:.

" File Types
autocmd BufNewFile,BufRead *.md set filetype=markdown
autocmd BufNewFile,BufRead .bash_aliases set filetype=sh

" Mapping
map ; :
noremap ;; ;
let mapleader=","
map <leader>b :Buffers<CR>
map <leader>bo :browse old<CR>
map <leader>d "+d
map <leader>e :Files<CR>
map <leader>n :set relativenumber<CR>
map <leader>nn :set norelativenumber<CR>
map <leader>p "+p
map <leader>rc :e $MYVIMRC<CR>
map <leader>s :source $MYVIMRC<CR>
map <leader>w :set list!<CR>
map <leader>y "+y
map <leader>yy ggVG"+y
nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<CR>
nnoremap <C-n> :bnext<CR>
nnoremap <C-p> :bprevious<CR>
nnoremap \ :w<CR>

" Theme
colorscheme OceanicNext
hi CursorLineNR guifg=#ffffff

" Plugin Settings
let g:airline_theme='oceanicnext'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:dart_style_guide = 2
let g:dart_format_on_save = 1
