" vim
set nocompatible

" vim-plug
call plug#begin()
Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'othree/yajs.vim', { 'for': 'javascript' }
call plug#end()

" general config
set number
set relativenumber
set history=100
set showmode
set visualbell
set autoread
set hidden
set autoindent
set smarttab
set noet
set showmatch
set backspace=indent,eol,start
set scrolloff=2
set laststatus=2
set cursorline
set incsearch
set hlsearch
set showcmd
set ignorecase
set smartcase
set splitbelow
set splitright
set wildmode=longest,list,full
set wildmenu

" mapping
let mapleader=","
map <leader>s :source $MYVIMRC<CR>
map <leader>rc :tabnew $MYVIMRC<CR>
nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<CR>
nnoremap <Up> <nop>
nnoremap <Down> <nop>
nnoremap <Left> <nop>
nnoremap <Right> <nop>

" theme
set t_Co=256
colorscheme solarized
set background=dark
let g:airline_theme='solarized'
let g:airline#extensions#branch#enabled = 1

" CtrlP
let g:ctrlp_max_files = 0
let g:ctrlp_max_depth = 40
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }
