" General Configuration
set nocompatible
filetype indent plugin on
syntax on
set nobackup
set nowritebackup
set noswapfile
set number
set relativenumber
set history=500
set showmode
set visualbell
set autoread
set hidden
set autoindent
set copyindent
set smarttab
set noet
set tabstop=4
set shiftwidth=4
set showmatch
set backspace=indent,eol,start
set scrolloff=5
set laststatus=2
set cursorline
set incsearch
set hlsearch
set showcmd
set ignorecase
set smartcase
set splitbelow
set splitright
set wildmode=longest,list,full
set wildmenu
set timeoutlen=1000 ttimeoutlen=0
set completeopt+=noinsert
set updatetime=100

" File Types
autocmd BufNewFile,BufRead *.md set filetype=markdown

" Mapping
map ; :
let mapleader=","
map <leader>s :source $MYVIMRC<CR>
map <leader>rc :e $MYVIMRC<CR>
map <leader>bo :browse old<CR>
nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<CR>
nnoremap <C-n> :bnext<CR>
nnoremap <C-p> :bprevious<CR>
nnoremap \ :w<CR>

" Theme
colorscheme OceanicNext

" Plugin Settings
let g:airline_theme='oceanicnext'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
