# Use Vim as the editor.
export VISUAL=vim
export EDITOR="$VISUAL"

# FZF.
export FZF_DEFAULT_COMMAND="rg -g '!*bower_components*' --files"

# Ensure Homebrew packages are first in the PATH.
export PATH="/usr/local/sbin:$PATH"

# ANSI colours in iTerm2.
export CLICOLOR=1

# Git integration
source ~/.dotfiles/git/git-completion.bash
source ~/.dotfiles/git/git-prompt.bash
export PS1='\[\033[1;30m\]\h \[\033[1;36m\]$? \[\033[1;34m\]\W$(__git_ps1 " \[\033[1;32m\]%s")\[\033[1;30m\] >\[\033[0m\] '

# Vim Mode for the command prompt.
set -o vi

# Aliases and clipboard expansions.
alias a='alias'
alias ba='vim ~/.bash_aliases'
alias brc='vim ~/.dotfiles/bash/bashrc'
function c() { local dir;dir=$(find ${1:-.} \( -path '*/\.*' -o -path '*/node_modules*' -o -path '*/bower_components*' \) -prune -o -type d -print 2> /dev/null | fzf +m) && cd "$dir"; }
function cache() { echo -n "http://webcache.googleusercontent.com/search?q=cache:" | pbcopy; }
alias cc='cd -'
alias cdo='cd ~/.dotfiles'
alias cdoc='cd ~/Documents'
alias cde='cd ~/Desktop'
alias cl='clear'
function e() { local file && file=$(fzf -m); if test -r "$file"; then vim $file; fi; }
alias f="rg -g '!*bower_components*'"
alias g='git status'
alias ga='git add -p'
alias gaa='git add .'
alias gb='git branch'
alias gc='git commit'
alias gcam='git commit --amend'
alias gcl='git clone'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcon='git config --list'
function gcor() { git checkout -t origin/$1; }
alias gcp='git cherry-pick'
alias gd='git diff'
alias gds='git diff --staged'
alias gi='git init'
alias gl='git log'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpo='git push -u origin'
alias gpu='git pull'
alias gpur='git pull --rebase'
function gr() { git rebase -i HEAD~$1; }
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias gre='git reset'
alias greh='git reset --hard'
alias grm='git rebase master'
alias grs='git rebase --skip'
alias gs='git show'
function gsa() { git submodule add $1 vim/pack/packages/start/${1//https:\/\/github.com\/[a-zA-Z0-9-]*\/}; }
function gsd() { git submodule deinit vim/pack/packages/start/$1; }
function gsi() { git submodule init vim/pack/packages/start/$1; }
alias gss='git submodule status'
alias gst='git stash -u'
alias gsta='git stash apply'
alias gstl='git stash list'
alias gsu='git submodule update --recursive'
alias gsui='git submodule update --init --recursive'
alias h='sudo vim /etc/hosts'
alias hi='history | grep'
function lorem() { echo -n "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus, metus id molestie laoreet, magna eros aliquet neque, a mattis nisl nibh ut lacus. Fusce lobortis aliquam massa a adipiscing. Mauris sed nunc dui, quis molestie nunc." | pbcopy; }
alias l='ls -ahl'
alias lp='ls -ahl ~/.dotfiles/vim/pack/packages/start'
alias m='man'
alias mc='make clean'
alias md='make distclean'
alias mr='make run'
alias mt='make test'
alias p='pwd'
alias rmr='rm -rfv'
alias so='source ~/.dotfiles/bash/bash_profile'
function shrug() { echo -n "¯\_(ツ)_/¯" | pbcopy; }
alias s='svn status'
alias sc='svn commit'
alias sd='svn diff | colordiff'
alias sr='svn revert -R'
alias su='svn update'
alias t='tmux ls'
alias ta='tmux attach -t'
alias tk='tmux kill-session -t'
alias tn='tmux new -s'
alias te='phpunit'
function tracimg() { echo -n "[[Image($1.png, 100%)]]" | pbcopy; }
alias ty='type'
alias v='vim'
alias vrc='vim ~/.dotfiles/vim/vimrc'
alias ya='yarn add'
alias yga='yarn global add'
alias ygr='yarn global remove'
alias yi='yarn install'
alias yr='yarn remove'
alias ys='yarn start'
alias zomg='git reset --hard && git clean -f -d'

